fix: tag include "#" Special character show 404
xianmin/hugo-theme-jane pull request #84
Opened 2018-07-20 08:36 UTC by xianmin

If I have a tag named `C#`, the url is `http://localhost:1313/tags/c#/` , this url show 404 page.

`#` sign in url is Special characters. Then I change the `#` to `%23`, Then it works.

This PR purpose is to solve this problem. 

I am not sure whether there is a better solution.

And should we fix this bug?

2018-07-20 09:46 UTC, shaform commented
This seems more like a bug of Hugo itself, but I don't object to fix it like this.

See also:
1. https://github.com/gohugoio/hugo/issues/4519
2. https://discourse.gohugo.io/t/sanitizing-category-names/11087

2018-07-20 09:49 UTC, shaform commented
It looks like hugoThemes is using netlify. So changing the exampleSite this way might cause build failure as described on the discourse discussion above.

2018-07-20 11:22 UTC, Zebradil requested changes
What about others special characters? I'd use something like URLEncode instead.

2018-07-20 12:06 UTC, shaform commented
Looks like this would be fixed by https://github.com/gohugoio/hugo/pull/4388

2018-07-20 14:21 UTC, xianmin commented
Yes, if hugo could fix this problem, that would be great.

This is a special problem. I think my fix code is a little ugly.

Put this on hold temporarily.

2018-10-18 14:18 UTC, shaform commented
Seems like Hugo already merged the related changes now. But it appears that the latest Hugo would make the url of tag `c#` as `http://localhost:1313/tags/c`.

2024-01-05 08:41 UTC, closed without merging